<?php

return [
 'people_search' => [
    'base_url' => 'https://propeoplesearch.com/',
    'slugs' => [
       'search' => 'ld/people/default/processing',
       'search-result' => 'ld/people/default/loading-results',
    ],
    'tokens' => [
        'search' => env('TARGET_URL_SEARCH_TOKEN', 'eyJpdiI6Ii8rUWlhRU4vK0tWa0VscjhzZGNCTVE9PSIsInZhbHVlIjoiZ3RVRXYzSzN2ZU1ZTFdqbW02azdnWlhEQnRuL05kbnNQWXJ1ejdDdWJXVCs1SWFXd1pnVThqNGxncUVubGRlK0orZjluMll6YTI0VFJMRU9EVyszYTlpcy9kLytUeE81c0FqVmJMK2lEc3B3TFFibVZJTnl3d0RkUmJQSTdHZjgiLCJtYWMiOiI4OGZkNzI0OWFmMTQ5ZGUyNzdkYjk0MDE4ZjFjN2FlMTZjMTg0ZDQzNjcyODg0MzA4MzA4MGY5MzZkMTFkYzc4In0%3D; propeoplesearch_session=eyJpdiI6IldyOWtDY0ljdytXbkFSS0lPRXNza2c9PSIsInZhbHVlIjoiSFZseFBEZ0lKT0I1Z05JQnJ0bUVJT0d5dW9GaXdFWkdQMHN0YVo4ck1zUCtUcWc3RndVeWZSaDF5SjdPK2xMekZob1Y0L2Q0bnIzd1NBUVFpV0I0MzhjSGsvcjlSQWE1Nm5sRHR1Q0hidjdEdVJQM2NFNHBkVmR0MjIvOXdvM0ciLCJtYWMiOiI5MjkyZDM0NTZjNGZjNTkwNGRlZmI1NmZjNDNlYjJlNWM0YTI5NzM3M2Y5OWYxY2VkOTMwYTQyZjBhZGRkMWJkIn0%3D'),
        'result' => env('TARGET_URL_RESULT_TOKEN','eyJpdiI6IjF2QjJnQWxFeHdBTWlRT1VycWZ0Z2c9PSIsInZhbHVlIjoiTkYvcDBXOTVxMnV2Z1FxbDg5QklDOTI1bk9Cd3BOYUozZ2w3TEcwblhLaXhkSDMvL1llbVBsRkVYUVV4OXU1cXowNWtqSzI4cWZYLzBPMVh3bENuOUdjMjB4N2RXdG1KazB4WG9zNG05L3ZyajJ3OEtrVmxSVlJEYnF5OEJHb2MiLCJtYWMiOiI2NTdmYjdlMGZhN2Y5MWNkMmY4NjBiY2Y4MWFkMGQzNGI2OGIwMWQwYmQ1ZDRkM2U3Y2JhODRmN2Q3ZWI1NDZjIn0%3D; propeoplesearch_session=eyJpdiI6IjZ5SHJXME50ZktCUXRlTHdTc202S2c9PSIsInZhbHVlIjoiSVlRc3B0YjB2MjErRUU0Rnl3WlhGOVpMbnNPRWRpOTNNbVNsUTV5N1YvM01lNlZkRnZZeGJmWXBTaFNNUm8vS08xeVl2UFlDb2VHdkhHN0dvanpFSW5yZEg5aVpxb3l6dnVBNExtZEwySE9UaFlOZUhCZ2ladlIyRStMaTFTRFMiLCJtYWMiOiI0Zjk0YTlhMTFjOGVjYzhmZDVmNzdmNzliNDI3NDBjZWRlMjhkYTA0OGRiMzMzOTA5ODA0NGVhNmEwMTNjZmU3In0%3D')
    ]
 ]   

];
